### PR TITLE
[Feature Request] Add "join" function

### PR DESCRIPTION
**Pull request by omrilotan**

### CODE REVIEW

**Comment by 75lb** [comment]
The `.toString()` method is a native, standardised method enabling a plain object (e.g. the byteSize output) to produce a string in string interpolation contexts. 

```js
const size = byteSize(1580) // returns an object implementing the .toString() method
const str = `Size: ${size}` // string interpolation context invokes the .toString() method
```

The language standard `.toString()` method does not accept an argument, so I won't be changing the current implementation.

Is the below use case not adequate? 

```js
> const { value, unit }  = byteSize(1580, { units: 'iec_octet' })
> `${value} XYZ ${unit}`
'1.5 XYZ Kio'
```

**Comment by omrilotan** [comment]
Sure. I know that it is possible using current implementation, but it would be possible to omit variable deceleration in consumption.
```js
const { value, unit }  = byteSize(1580);

`${value}${unit}`
```
VS
```js
byteSize(1580).join('');
```

I understand why you would not like to expand on native-like `toString` method, even though adding optional argument will not **break** classical `toString` interface.

Anyway, thanks for the attention :)

**Comment by omrilotan** [comment]
@75lb thoughts?
Should I close this issue?

**Comment by 75lb** [comment]
not had chance to check your latest commits but it's not something the
library desperately needs IMO.. the suggested .join method makes an
assumption the number will always come before the unit - the current
interface intentionally avoids this and any other assumption (the byteSize
method returns two distinct values and you present them however you like,
in any order with any delimiter)..

**Comment by omrilotan** [comment]
Fair enough. Thank you for the attention

**Pull request closed without merging**
